### ISSUE TITLE
Ramp.js does not exist

### ISSUE THREAD

**Issue by Jaaneek** [intergi/pw-react-component#9]
This line causes errors with vite, it should be changed to https://github.com/intergi/pw-react-component/blob/main/index.js file

https://github.com/intergi/pw-react-component/blob/9d05eb97ed0810dd04d280d53731c6c3e802be3a/package.json#L24

**Comment by Jaaneek** [comment]
Per documentation on https://docs.npmjs.com/cli/v9/configuring-npm/package-json#main.
"main" should point to a file that the primary entry point to your program. In your case this is the [index](https://github.com/intergi/pw-react-component/blob/main/index.js).js file.
You can also delete this field since "main" is set to index.js by default

**Comment by jarrettabello** [comment]
Thanks for the heads up. We are just seeing the issues here in the repo and are working on a process to address incoming issues. As a development team we are used to processing issues that come through bug reports through our technical solutions team - so this is new to us!! Make sure to reach out to your technical solutions contact if you continue to have issues!

**Comment by nicomvaldez** [comment]
Thanks for the heads up. Fixed here https://github.com/intergi/pw-react-component/pull/11. Closing the issue
